name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build
        run: npm run build
        
      - name: Copy service workers to root
        run: |
          # Check if the service worker files exist before copying
          if [ -f "out/naderos/OneSignalSDKWorker.js" ]; then
            cp out/naderos/OneSignalSDKWorker.js out/
            echo "✓ Copied OneSignalSDKWorker.js to root"
          else
            echo "⚠ OneSignalSDKWorker.js not found in out/naderos/"
          fi
          
          if [ -f "out/naderos/OneSignalSDKUpdaterWorker.js" ]; then
            cp out/naderos/OneSignalSDKUpdaterWorker.js out/
            echo "✓ Copied OneSignalSDKUpdaterWorker.js to root"
          else
            echo "⚠ OneSignalSDKUpdaterWorker.js not found in out/naderos/"
          fi
          
          # List files to verify
          echo "Files in out/:"
          ls -la out/
          echo "Files in out/naderos/:"
          ls -la out/naderos/ || echo "naderos directory not found"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
